---
- name: Install Java
  apt:
    name: "{{ java_package }}"
    state: present

- name: Verify Java installation
  command: java -version
  register: java_version
  changed_when: false
  failed_when: false

- name: Show Java version
  debug:
    var: java_version.stderr_lines
