---
- name: Deploy BoardGame Application using Docker
  hosts: boardgame
  become: yes

  vars:
    app_dir: "/home/ubuntu/AWS/Automating-Secure-Deployment-of-Board-game-Listing-WebApp-on-AWS/BoardGame"
    image_name: "boardgame"
    image_tag: "1.0"
    container_name: "boardgame-app"
    host_port: "8081"
    container_port: "8080"
    security_reports_dir: "/home/ubuntu/AWS/Automating-Secure-Deployment-of-Board-game-Listing-WebApp-on-AWS/security-reports"
    dependency_check_data_dir: "/home/ubuntu/AWS/Automating-Secure-Deployment-of-Board-game-Listing-WebApp-on-AWS/.dependency-check-data"
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - openjdk-17-jdk
          - maven
          - docker.io
          - git
          - curl
          - unzip
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Fix project ownership before Maven build
      file:
        path: "{{ app_dir }}"
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Build Maven package using Java 17 as ubuntu user
      shell: |
        sudo -H -u ubuntu bash -lc '
          cd {{ app_dir }}
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          java -version
          mvn -version
          mvn clean package -DskipTests
        '
    - name: Build Docker image
      command: docker build -t {{ image_name }}:{{ image_tag }} .
      args:
        chdir: "{{ app_dir }}"

    - name: Stop old container if running
      command: docker stop {{ container_name }}
      ignore_errors: yes

    - name: Remove old container if exists
      command: docker rm {{ container_name }}
      ignore_errors: yes

    - name: Run BoardGame container
      command: docker run -d -p {{ host_port }}:{{ container_port }} --name {{ container_name }} {{ image_name }}:{{ image_tag }}

    - name: Wait for BoardGame application to start
      pause:
        seconds: 15

    - name: Verify BoardGame application health
      uri:
        url: "http://localhost:8081"
        method: GET
        status_code: 200
      register: boardgame_health

    - name: Show BoardGame application health status
      debug:
        msg: "BoardGame application is running successfully with HTTP status {{ boardgame_health.status }}"

    - name: Check running containers
      command: docker ps
      register: docker_ps_output

    - name: Show Docker running containers
      debug:
        var: docker_ps_output.stdout_lines
